version: '3'

services:
  backend:
    build: .
    container_name: django_backend
    restart: always
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    depends_on:
      - backend